### ISSUE TITLE
Doesn't colour more than 100 IDs

### ISSUE THREAD

**Issue by kreeyateee** [jenschristianschroder/PCF-SVG-Control#3]
Hey,

For some reason when using this - I can't get it to colour more than 100 items successfully. Seems to be a hard limit.

Tried splitting up the controls into 4 separate SVGs (218 items total to colour) and it won't do it. Is this a code issue? I couldn't find anything referencing anything that should have limits and your for loop goes through the length of the object passed into it.

**Comment by jenschristianschroder** [comment]
@kreeyateee 

Sorry for being so slow to reply

There is no pagination implemented so if your data source returns paginated results then that could be the cause for the behavior.

The limitation should be on the data source and canvas app configuration and the max number of records that can be returned

What is your data source?

Can you share your SVG?

**Comment by kreeyateee** [comment]
Hey thanks for getting back to me.

In the end I had to split the data source into 100 and split the svg up.

I had an svg with 218. Suppose it might be too do with the input into the
function I couldn't get anything to work.

Michael
