### ISSUE TITLE
Native PowerApps possible?

### ISSUE THREAD

**Issue by ericthomas1** [jenschristianschroder/PCF-SVG-Control#6]
Hi @jenschristianschroder ,

Awesome work! I'm curious if you packaged as PCF / Solution to make the tool portable or if indeed it requires some specific coding in the PCF. 

Basically, **could this functionality be accomplished in native PowerApps or is the PCF required?**

Thank you

**Comment by jenschristianschroder** [comment]
sorry for late reply.

Similar functionality can be achieve in native power apps.

Here is a Power CAT video that show how you can do something similar https://www.youtube.com/watch?v=L_EA0eOgnog

**Comment by jenschristianschroder** [comment]
@ericthomas1 

> sorry for late reply.
> 
> Similar functionality can be achieve in native power apps.
> 
> Here is a Power CAT video that show how you can do something similar https://www.youtube.com/watch?v=L_EA0eOgnog
